from django.db import models

# Create your models here


class UploadedFile(models.Model):
    file = models.FileField()
    created_at = models.DateTimeField(auto_now_add=True)


class Sippeers(models.Model):
    name = models.CharField(unique=True, max_length=10)
    ipaddr = models.CharField(max_length=15)
    port = models.IntegerField()
    regseconds = models.IntegerField()
    defaultuser = models.CharField(max_length=10)
    fullcontact = models.CharField(max_length=80)
    regserver = models.CharField(max_length=20)
    useragent = models.CharField(max_length=100)
    lastms = models.IntegerField()
    host = models.CharField(max_length=40)
    type = models.CharField(max_length=6)
    context = models.CharField(max_length=40)
    permit = models.CharField(max_length=40)
    deny = models.CharField(max_length=40)
    secret = models.CharField(max_length=40)
    md5secret = models.CharField(max_length=40)
    remotesecret = models.CharField(max_length=40)
    transport = models.CharField(max_length=7)
    dtmfmode = models.CharField(max_length=9)
    directmedia = models.CharField(max_length=6)
    nat = models.CharField(max_length=50, blank=True, null=True)
    callgroup = models.CharField(max_length=40)
    pickupgroup = models.CharField(max_length=40)
    language = models.CharField(max_length=40)
    disallow = models.CharField(max_length=40)
    allow = models.CharField(max_length=40)
    insecure = models.CharField(max_length=40)
    trustrpid = models.CharField(max_length=3)
    progressinband = models.CharField(max_length=5)
    promiscredir = models.CharField(max_length=3)
    useclientcode = models.CharField(max_length=3)
    accountcode = models.CharField(max_length=40)
    setvar = models.CharField(max_length=40)
    callerid = models.CharField(max_length=40)
    amaflags = models.CharField(max_length=40)
    callcounter = models.CharField(max_length=3)
    busylevel = models.IntegerField()
    allowoverlap = models.CharField(max_length=3)
    allowsubscribe = models.CharField(max_length=3)
    videosupport = models.CharField(max_length=3)
    maxcallbitrate = models.IntegerField()
    rfc2833compensate = models.CharField(max_length=3)
    mailbox = models.CharField(max_length=40)
    session_timers = models.CharField(db_column='session-timers', max_length=9)  # Field renamed to remove unsuitable characters.
    session_expires = models.IntegerField(db_column='session-expires')  # Field renamed to remove unsuitable characters.
    session_minse = models.IntegerField(db_column='session-minse')  # Field renamed to remove unsuitable characters.
    session_refresher = models.CharField(db_column='session-refresher', max_length=3)  # Field renamed to remove unsuitable characters.
    t38pt_usertpsource = models.CharField(max_length=40)
    regexten = models.CharField(max_length=40)
    fromdomain = models.CharField(max_length=40)
    fromuser = models.CharField(max_length=40)
    qualify = models.CharField(max_length=40)
    defaultip = models.CharField(max_length=40)
    rtptimeout = models.IntegerField()
    rtpholdtimeout = models.IntegerField()
    sendrpid = models.CharField(max_length=3)
    outboundproxy = models.CharField(max_length=40)
    callbackextension = models.CharField(max_length=40)
    timert1 = models.IntegerField()
    timerb = models.IntegerField()
    qualifyfreq = models.IntegerField()
    constantssrc = models.CharField(max_length=3)
    contactpermit = models.CharField(max_length=40)
    contactdeny = models.CharField(max_length=40)
    usereqphone = models.CharField(max_length=3)
    textsupport = models.CharField(max_length=3)
    faxdetect = models.CharField(max_length=3)
    buggymwi = models.CharField(max_length=3)
    auth = models.CharField(max_length=40)
    fullname = models.CharField(max_length=40)
    trunkname = models.CharField(max_length=40)
    cid_number = models.CharField(max_length=40)
    callingpres = models.CharField(max_length=21)
    mohinterpret = models.CharField(max_length=40)
    mohsuggest = models.CharField(max_length=40)
    parkinglot = models.CharField(max_length=40)
    hasvoicemail = models.CharField(max_length=3)
    subscribemwi = models.CharField(max_length=3)
    vmexten = models.CharField(max_length=40)
    autoframing = models.CharField(max_length=3)
    rtpkeepalive = models.IntegerField()
    call_limit = models.IntegerField(db_column='call-limit')  # Field renamed to remove unsuitable characters.
    g726nonstandard = models.CharField(max_length=3)
    ignoresdpversion = models.CharField(max_length=3)
    allowtransfer = models.CharField(max_length=3)
    dynamic = models.CharField(max_length=3)
    ucontext = models.CharField(max_length=12)
    peer = models.CharField(max_length=30)
    gravar = models.CharField(max_length=3)
    fila = models.CharField(max_length=10)
    istdm = models.BigIntegerField()
    tdmport = models.CharField(max_length=10)

    class Meta:
        managed = False
        db_table = 'sippeers'